name: Test API

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check Mongo secret
        run: |
          if [ -z "$MONGODB_URI" ]; then
            echo "MONGODB_URI is missing"
            exit 1
          else
            echo "MONGODB_URI is set"
          fi

      - name: Run Jest tests
        run: npm test